### ISSUE TITLE
0x83 acc speed(mkz car)

### ISSUE THREAD

**Issue by woshikangfei** [ingenieroariel/abraham#58] opened 2017-03-10 03:35 UTC
acc change speed
button +
current:083 00 00 00 00 00 00 00 00
changes:083 00 00 00 20 00 00 00 00

button -
current:083 00 00 00 00 00 00 00 00
changes:083 00 00 00 10 00 00 00 00

**Comment by eldarial** [comment] 2017-03-10 03:44
is not this a duplicate of #10 ?

**Comment by ingenieroariel** [comment] 2017-03-10 03:46
Yep, duplicate, closing this one.

**Closed by ingenieroariel** 2017-03-10 03:46 UTC
